{
 "title": "Minar Health Stats (Power, Temperature, Fan-Speed)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Core Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cpu_temp",
     "select": [
      [
       { "params": [ "core_temp_Core_0" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "cpu_temp",
     "select": [
      [
       { "params": [ "core_temp_Core_1" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "cpu_temp",
     "select": [
      [
       { "params": [ "core_temp_Core_2" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "cpu_temp",
     "select": [
      [
       { "params": [ "core_temp_Core_3" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Power Consumption (Watts)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.0",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.1",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.2",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.3",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.4",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.5",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.6",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.7",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_0",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_1",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_2",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_3",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "All GPU Temperatures (℉)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.0",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.1",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.2",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.3",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.4",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.5",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.6",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.7",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_0",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_1",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_2",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_3",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "All GPU Fan-Speeds   (unit=%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.0",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.1",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.2",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.3",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.4",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.5",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.6",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.7",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_0",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_1",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_2",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_3",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AMD Hashrates (MH/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "amd0",
     "measurement": "mhs.amd",
     "select": [
      [
       { "params": [ "hashrate_amd0" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "amd1",
     "measurement": "mhs.amd",
     "select": [
      [
       { "params": [ "hashrate_amd1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "amd2",
     "measurement": "mhs.amd",
     "select": [
      [
       { "params": [ "hashrate_amd2" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "amd3",
     "measurement": "mhs.amd",
     "select": [
      [
       { "params": [ "hashrate_amd3" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nvidia Total Hashrate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mhs.nvidia",
     "select": [
      [
       { "params": [ "total_hash_rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nvidia Hashrates (MH/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "nvidia0",
     "measurement": "mhs.nvidia",
     "select": [
      [
       { "params": [ "hashrate_nvidia0" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "nvidia1",
     "measurement": "mhs.nvidia",
     "select": [
      [
       { "params": [ "hashrate_nvidia1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "nvidia2",
     "measurement": "mhs.nvidia",
     "select": [
      [
       { "params": [ "hashrate_nvidia2" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "nvidia3",
     "measurement": "mhs.nvidia",
     "select": [
      [
       { "params": [ "hashrate_nvidia3" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "nvidia4",
     "measurement": "mhs.nvidia",
     "select": [
      [
       { "params": [ "hashrate_nvidia4" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "nvidia5",
     "measurement": "mhs.nvidia",
     "select": [
      [
       { "params": [ "hashrate_nvidia5" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "nvidia6",
     "measurement": "mhs.nvidia",
     "select": [
      [
       { "params": [ "hashrate_nvidia6" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "nvidia7",
     "measurement": "mhs.nvidia",
     "select": [
      [
       { "params": [ "hashrate_nvidia7" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AMD Total Hashrate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mhs.amd",
     "select": [
      [
       { "params": [ "total_hash_rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.0",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.0",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.0",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.1",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.1",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.1",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  3",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.2",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.2",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.2",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  4",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.3",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.3",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.3",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.4",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.4",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.4",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  6",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.5",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.5",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.5",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  7",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.6",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.6",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.6",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  8",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.7",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.7",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.7",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AMD 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "amd_0",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_0",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_0",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AMD 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "amd_1",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_1",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_1",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AMD 3",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "amd_2",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_2",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_2",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AMD 4",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "amd_3",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_3",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_3",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}